// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Additional terms: see LICENSE-ADDITIONAL-TERMS.md

import { ExternalIconType } from "components/atoms/ExternalIcon/ExternalIcon";

export interface PredefinedTag {
  name: string;
  icon?: string;
  externalIcon?: ExternalIconType;
}

export const generalTagList: PredefinedTag[] = [
  { name: 'Gaming', icon: '🎮' },
  { name: 'Chill', icon: '☕' },
  { name: 'Work', icon: '💼' },
  { name: 'Study', icon: '📚' },
  { name: 'Movies', icon: '🎬' },
  { name: 'TV Shows', icon: '📺' },
  { name: 'Sports', icon: '⚽' },
  { name: 'Fitness', icon: '💪' },
  { name: 'Coding', icon: '⌨️' },
  { name: 'Memes', icon: '😂' },
  { name: 'News', icon: '📰' },
  { name: 'Discussion', icon: '💬' },
  { name: 'Support', icon: '🤝' },
  { name: 'Hobbies', icon: '🎣' },
  { name: "Help", icon: "❓" },
  { name: "Question", icon: "❔" },
  { name: "Idea", icon: "💡" },
  { name: "Poll", icon: "📊" },
  { name: "Event", icon: "📅" },
  { name: "Announcement", icon: "📢" },
  { name: "Feedback", icon: "📝" },
  { name: "Guide", icon: "🧭" },
  { name: "Tutorial", icon: "🎓" },
  { name: "Introductions", icon: "👋" },
  { name: "Community", icon: "👥" },
  { name: "Updates", icon: "🔄" },
  { name: "General", icon: "🌐" },
  { name: "Pinned", icon: "📌" },
  { name: "Official", icon: "✔️" },
  { name: "Welcome", icon: "🤗" },
  { name: "Article", icon: "📄" },
  { name: "Blog", icon: "✍️" },
  { name: "Video", icon: "🎬" },
  { name: "Image", icon: "🖼️" },
  { name: "Audio", icon: "🎧" },
  { name: "Music", icon: "🎶" },
  { name: "Podcast", icon: "🎙️" },
  { name: "Link", icon: "🔗" },
  { name: "Code", icon: "⌨️" },
  { name: "Technology", icon: "💻" },
  { name: "Data", icon: "📈" },
  { name: "Review", icon: "⭐" },
  { name: "Story", icon: "📖" },
  { name: "Meme", icon: "😂" },
  { name: "Livestream", icon: "🔴" },
  { name: "Love", icon: "❤️" },
  { name: "Like", icon: "👍" },
  { name: "Funny", icon: "😄" },
  { name: "Thanks", icon: "🙏" },
  { name: "Congrats", icon: "🎉" },
  { name: "Celebrate", icon: "🥳" },
  { name: "Inspiration", icon: "🌟" },
  { name: "Science", icon: "🔬" },
  { name: "Art", icon: "🎨" },
  { name: "Design", icon: "✏️" },
  { name: "Books", icon: "📚" },
  { name: "Food", icon: "🍕" },
  { name: "Cooking", icon: "🍳" },
  { name: "Travel", icon: "✈️" },
  { name: "Health", icon: "⚕️" },
  { name: "Finance", icon: "💰" },
  { name: "Business", icon: "💼" },
  { name: "Education", icon: "🏫" },
  { name: "Nature", icon: "🌳" },
  { name: "Pets", icon: "🐾" },
  { name: "DIY", icon: "🛠️" },
  { name: "Photography", icon: "📷" },
  { name: "Fashion", icon: "👗" },
  { name: "Cars", icon: "🚗" },
  { name: "Space", icon: "🚀" },
  { name: "AI", icon: "🤖" },
  { name: "Crypto", icon: "🪙" },
  { name: "Environment", icon: "🌍" },
  { name: "New", icon: "✨" },
  { name: "Hot", icon: "🔥" },
  { name: "Trending", icon: "↗️" },
  { name: "Solved", icon: "✅" },
  { name: "Bug", icon: "🐛" },
  { name: "Feature", icon: "🎁" },
  { name: "Project", icon: "🏗️" },
  { name: "Challenge", icon: "🏆" },
  { name: "Learning", icon: "🧠" },
  { name: "Sharing", icon: "🤝" },
  { name: "Sale", icon: "🏷️" },
  { name: "Job", icon: "🧑‍💼" },
  { name: "Beginner", icon: "🌱" },
  { name: "Advanced", icon: "🏅" },
  { name: "Tips", icon: "🔑" },
  { name: "HowTo", icon: "🔧" },
  { name: "Meta", icon: "⚙️" },
  { name: "Security", icon: "🔒" },
  { name: "Tools", icon: "🧰" },
  { name: "Showcase", icon: "💎" },
  { name: "Meetup", icon: "📍" },
  { name: "Research", icon: "🧐" },
  { name: "Giveaway", icon: "🎟️" },
  { name: "AMA", icon: "🎤" },
  { name: "OffTopic", icon: "🤪" },
  { name: "Mobile", icon: "📱" },
  { name: "Web", icon: "🕸️" },
  { name: "Cloud", icon: "☁️" },
  { name: "Server", icon: "🗄️" },
  { name: "API", icon: "🔌" },
  { name: "Beta", icon: "🧪" },
  { name: "Friends", icon: "👬" },
  { name: 'He/Him', icon: '👨' },
  { name: 'She/Her', icon: '👩' },
  { name: 'They/Them', icon: '🧑' },
];

export const web3TagList: PredefinedTag[] = [
  { name: "DeFi", icon: "💸" },
  { name: "NFT", icon: "🖼️" },
  { name: "DAO", icon: "🏛️" },
  { name: "Web3", icon: "🌐" },
  { name: "Metaverse", icon: "👓" },
  { name: "Smart Contracts", icon: "📜" },
  { name: "Wallet", icon: "🔑" },
  { name: "Tokenomics", icon: "📊" },
  { name: "Staking", icon: "🔒" },
  { name: "Yield Farming", icon: "🚜" },
  { name: "Liquidity", icon: "💧" },
  { name: "DEX", icon: "🔄" },
  { name: "Oracle", icon: "🔮" },
  { name: "Gas Fees", icon: "⛽" },
  { name: "dApp", icon: "📱" },
  { name: "HODL", icon: "💪" },
  { name: "Diamond Hands", icon: "💎" },
  { name: "Paper Hands", icon: "🧻" },
  { name: "To The Moon", icon: "🚀" },
  { name: "FUD", icon: "😨" },
  { name: "FOMO", icon: "👀" },
  { name: "WAGMI", icon: "🫂" },
  { name: "NGMI", icon: "🤦" },
  { name: "Shill", icon: "📢" },
  { name: "Ape In", icon: "🦍" },
  { name: "Bullish", icon: "🐂" },
  { name: "Bearish", icon: "🐻" },
  { name: "Whale", icon: "🐋" },
  { name: "Rekt", icon: "💀" },
  { name: "UpOnly", icon: "⬆️" },
  { name: "Degen", icon: "😈" },
  { name: "Alpha", icon: "🎯" },
  { name: "GM", icon: "🌅" },
  { name: "GN", icon: "🌃" },
  { name: "LFG", icon: "💥" },
  { name: "DYOR", icon: "🧐" },
  { name: "Minting", icon: "✨" },
  { name: "Play-to-Earn", icon: "🏆" },
  { name: "GameFi", icon: "🕹️" },
  { name: "Governance", icon: "🗳️" },
  { name: "Audit", icon: "📋" },
  { name: "Airdrop", icon: "🪂" },
  { name: "Whitepaper", icon: "🗒️" },
  { name: "Roadmap", icon: "🗺️" },
  { name: "Layer 2", icon: "🧱" },
  { name: "Scalability", icon: "⚙️" },
  { name: "Interoperability", icon: "🤝" },
  { name: "ZK Proof", icon: "🤫" },
  { name: "Mining", icon: "⛏️" },
  { name: "Stablecoin", icon: "⚓" },
  { name: "Rug Pull", icon: "🐍" },
  { name: "Bagholder", icon: "🛍️" },
  { name: "Flipping", icon: "🐬" },
  { name: "Mainnet", icon: "🟢" },
  { name: "Testnet", icon: "🧪" },
  { name: "Gasless", icon: "🆓" },
  { name: "Bridge", icon: "🌉" },
  { name: "Cross-Chain", icon: "🔗" },
  { name: "ReFi", icon: "🌱" },
  { name: "SheFi", icon: "👩‍💼" },
  { name: "Binance", externalIcon: "binance" },

  // Added SimpleChannels as regular predefined tags
  { name: 'Arbitrum', externalIcon: 'arbitrum' },
  { name: 'Avalanche', externalIcon: 'avalanche' },
  { name: 'Base', externalIcon: 'base' },
  { name: 'Binance Smart Chain', externalIcon: 'binance smart chain' },
  { name: 'Ethereum', externalIcon: 'ethereum' },
  { name: 'Fantom', externalIcon: 'fantom' },
  { name: 'Gnosis', externalIcon: 'gnosis' },
  { name: 'Linea', externalIcon: 'linea' },
  { name: 'LUKSO', externalIcon: 'lukso' },
  { name: 'Optimism', externalIcon: 'optimism' },
  { name: 'Polygon', externalIcon: 'polygon' },
  { name: 'Scroll', externalIcon: 'scroll' },
  { name: 'zkSync', externalIcon: 'zksync' },
  { name: 'Cardano', externalIcon: 'cardano' },
  { name: 'Solana', externalIcon: 'solana' },
];

export const predefinedTagList: PredefinedTag[] = [
  ...generalTagList,
  ...web3TagList,
];
