// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Additional terms: see LICENSE-ADDITIONAL-TERMS.md

import fs from 'node:fs';
import path from 'node:path';
import { defineConfig } from 'vite';
import type { ServerOptions } from 'vite';
import react from '@vitejs/plugin-react';
import svgr from 'vite-plugin-svgr';
import { nodePolyfills } from 'vite-plugin-node-polyfills';
import { absoluteSocialMeta } from './vite/absoluteSocialMeta';
import { baseUrlResolve } from './vite/baseUrlResolve';
import { htmlEntryScripts } from './vite/htmlEntryScripts';
import { serviceWorker } from './vite/serviceWorker';

// The `browserslist.production` floors from package.json, in esbuild's
// notation. Keep the two lists in sync.
const BUILD_TARGET = ['chrome67', 'edge79', 'firefox68', 'opera54', 'safari14'];

// react-scripts' @svgr/webpack options, verbatim
// (node_modules/react-scripts/config/webpack.config.js:392-401). `svgo: false`
// is load-bearing: svgr's default svgo pass strips `viewBox`.
const SVGR_OPTIONS = {
  svgo: false,
  titleProp: true,
  ref: true,
};

/**
 * HTTPS for the dev server, from the same env vars the CRA dev server used
 * (`run.sh start_https` exports them; the certs are generated by
 * `docker/build.sh`). Missing certs degrade to plain HTTP with a warning
 * rather than failing the server start.
 */
function devServerHttps(): ServerOptions['https'] {
  const { HTTPS, SSL_CRT_FILE, SSL_KEY_FILE } = process.env;
  if (HTTPS !== 'true' && !SSL_CRT_FILE && !SSL_KEY_FILE) return undefined;

  if (!SSL_CRT_FILE || !SSL_KEY_FILE) {
    console.warn('[vite] HTTPS requested but SSL_CRT_FILE/SSL_KEY_FILE are not both set — serving over HTTP');
    return undefined;
  }
  if (!fs.existsSync(SSL_CRT_FILE) || !fs.existsSync(SSL_KEY_FILE)) {
    console.warn(`[vite] certificate files not found (${SSL_CRT_FILE}, ${SSL_KEY_FILE}) — serving over HTTP`);
    return undefined;
  }
  return { cert: fs.readFileSync(SSL_CRT_FILE), key: fs.readFileSync(SSL_KEY_FILE) };
}

export default defineConfig({
  // Both HTML entries live at the repo root; `public/` stays copy-verbatim.
  root: __dirname,
  base: '/',
  publicDir: 'public',

  plugins: [
    react(),
    baseUrlResolve('src'),
    svgr({ include: '**/*.svg?react', svgrOptions: SVGR_OPTIONS }),
    // Scoped on purpose (§2.2, constraint 6): first-party code uses none of
    // this, it exists for transitive web3 dependencies. `process` and `global`
    // stay unpolyfilled — `src/common/` is dual-runtime (backend via the
    // `srv/common` symlink) and reads `process.env` through a `globalThis`
    // indirection that must keep resolving to nothing in the browser.
    nodePolyfills({
      include: ['buffer', 'stream', 'assert'],
      globals: { Buffer: true, global: false, process: false },
      protocolImports: false,
    }),
    htmlEntryScripts({
      'index.html': '/src/index.tsx',
      'index_cgid.html': '/src/index_cgid.tsx',
    }),
    // Only the legacy Azure pipelines set PUBLIC_URL; everywhere else this is
    // a no-op. See vite/absoluteSocialMeta.ts.
    absoluteSocialMeta(process.env.PUBLIC_URL),
    serviceWorker({
      swSrc: 'src/service-worker.ts',
      plugins: [baseUrlResolve('src')],
    }),
  ],

  resolve: {
    alias: [
      // Exact-match alias (webpack's `altcha-widget-element$`, §2.3): loads the
      // altcha bundle under a stub module name so its `.d.ts` — which augments
      // react/jsx-runtime and breaks JSX inference with @types/react 18 — never
      // enters the TS program. The stub lives in
      // src/types/altcha-widget-element.d.ts.
      { find: /^altcha-widget-element$/, replacement: 'altcha' },
      // @metamask/sdk declares `browser` (a UMD bundle) *and* `module` (its
      // **node** ESM build). Vite's resolver prefers an ESM `module` entry over
      // a non-ESM `browser` entry, so it pulls the node build into the browser
      // bundle — fs/child_process/tls/zlib get externalized and throw at
      // runtime. webpack's `mainFields: ['browser', 'module', 'main']` picks the
      // browser UMD build (verified against the CRA sourcemaps); pin the same
      // file here.
      {
        find: /^@metamask\/sdk$/,
        replacement: '@metamask/sdk/dist/browser/umd/metamask-sdk.js',
      },
    ],
  },

  build: {
    // Separate from CRA's `build/` so both stacks can be run side by side
    // until the Phase-3 cutover.
    outDir: 'build-vite',
    emptyOutDir: true,
    target: BUILD_TARGET,
    // nginx's cache/serve rules key on
    // `^/(fonts|icons|images|static|audio|downloads)/` (§10.4) — Vite's default
    // `assets/` would match none of them.
    assetsDir: 'static',
    // Preserves the CRA behavior (`IMAGE_INLINE_SIZE_LIMIT=5000`); CRA's
    // default was 10000, Vite's is 4096.
    assetsInlineLimit: 5000,
    // Always on, on every build path — the app is AGPL, shipping maps is
    // intentional. The precache excludes them (see vite/serviceWorker.ts).
    sourcemap: true,
    reportCompressedSize: false,
    rollupOptions: {
      input: {
        main: path.resolve(__dirname, 'index.html'),
        index_cgid: path.resolve(__dirname, 'index_cgid.html'),
      },
      output: {
        // Hex hashes keep the service worker's `dontCacheBustURLsMatching`
        // pattern (`/\.[0-9a-f]{8}\./`) meaningful; rollup's default base64
        // alphabet would never match it.
        hashCharacters: 'hex',
        entryFileNames: 'static/js/[name].[hash:8].js',
        chunkFileNames: 'static/js/[name].[hash:8].chunk.js',
        assetFileNames: (asset) =>
          asset.names?.some((name) => name.endsWith('.css'))
            ? 'static/css/[name].[hash:8].css'
            : 'static/media/[name].[hash:8][extname]',
      },
    },
  },

  server: {
    host: '0.0.0.0',
    // Load-bearing, not a preference: the service-worker registration manager
    // disables itself when the origin port is 3000 (§8.1,
    // src/data/appstate/serviceWorker.ts:26-28). Another port would enable the
    // SW against the dev server.
    port: 3000,
    strictPort: true,
    https: devServerHttps(),
  },

  // The entry scripts are injected into the HTML at transform time (see
  // vite/htmlEntryScripts.ts), which the dependency scanner does not see — name
  // them explicitly so dev-server cold starts pre-bundle properly.
  optimizeDeps: {
    entries: ['src/index.tsx', 'src/index_cgid.tsx'],
  },
});
