#!/bin/bash
# Disposable conformance instance: spins the selfhost compose stack under its
# own project name with throwaway secrets and volumes, waits until the API
# answers, and tears everything down again. The suite then runs with
#   CG_BASE_URL=http://127.0.0.1:18080 yarn test
#
# Usage: ./disposable-instance.sh {up|down|status}
#
# Requirements: docker with the selfhost images already built
# (docker/selfhost/selfhost.sh build), run from anywhere inside the repo.
# Coexists with a live cg-selfhost deployment on the same host: separate
# project (cg-conformance), separate volumes, loopback-only ports, no caddy,
# no blockchain profile (public RPCs are not hammered from CI).
#
# The instance is API-only: the frontend volume stays empty (nginx's
# instance-config injection hook skips missing files), which is fine because
# the conformance suite talks to /api/v2 only.
set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
DOCKER_DIR="$REPO_ROOT/docker"
ENV_FILE="$DOCKER_DIR/.env.conformance"
HTTP_PORT="${CONFORMANCE_HTTP_PORT:-18080}"

compose() {
  COMPOSE_PROFILES="calls" docker compose \
    -p cg-conformance \
    --env-file "$ENV_FILE" \
    -f "$DOCKER_DIR/docker-compose.selfhost.yml" \
    -f "$DOCKER_DIR/docker-compose.conformance.yml" \
    "$@"
}

rand() { openssl rand -hex "$1"; }

generate_env() {
  # Fresh secrets every time — the volumes are throwaway, so stale
  # credentials in a reused env file would only cause confusion.
  cat > "$ENV_FILE" <<EOF
# Generated by sdk/conformance/tools/disposable-instance.sh — throwaway.
CG_DOMAIN=127.0.0.1:${HTTP_PORT}
CG_ID_DOMAIN=127.0.0.1:${HTTP_PORT}
CG_ACME_EMAIL=conformance@invalid.example
CG_PUBLIC_IP=127.0.0.1
PG_SU_PASSWORD=$(rand 24)
PG_WRITER_PASSWORD=$(rand 24)
PG_READER_PASSWORD=$(rand 24)
PG_MEDIASOUP_PASSWORD=$(rand 24)
REDIS_PASSWORD=$(rand 24)
REDIS_SECRET=$(rand 24)
S3_SECRET=$(rand 48)
REDIS_MAXMEMORY=256mb
SEAWEED_VOLUME_LIMIT_MB=256
MEDIASOUP_DISABLE_LIBURING=true
BUILDER_UID=$(id -u)
BUILDER_GID=$(id -g)
CG_ENABLE_CALLS=true
CG_ENABLE_BLOCKCHAIN=false
PLATFORM_OPERATOR_USER_IDS=
CAPTCHA_PROVIDER=altcha
ALTCHA_HMAC_KEY=$(rand 32)
CG_RECAPTCHA_SITE_KEY=
GOOGLE_RECAPTCHA_SECRET_KEY=
SENDGRID_API_KEY=
EMAIL_FROM=no-reply@conformance.invalid
CG_ACTIVE_CHAINS=
QUIKNODE_ETH=
QUIKNODE_BSC=
QUIKNODE_MATIC=
QUIKNODE_XDAI=
QUIKNODE_FANTOM=
QUIKNODE_AVAX=
QUIKNODE_ARBITRUM=
QUIKNODE_OPTIMISM=
QUIKNODE_BASE=
INFURA_LINEA=
QUIKNODE_ARBITRUM_NOVA=
QUIKNODE_CELO=
QUIKNODE_POLYGON_ZKEVM=
QUIKNODE_SCROLL=
QUIKNODE_ZKSYNC=
QUIKNODE_LUKSO=
CG_GIPHY_API_KEY=
CG_WALLETCONNECT_PROJECT_ID=
TWITTER_API_KEY=
TWITTER_API_SECRET=
TWITTER_CALLBACK_URL=
TWITTER_OAUTH2_CLIENT_ID=
TWITTER_OAUTH2_CLIENT_SECRET=
MAILCHIMP_API_KEY=
MAILCHIMP_LIST_ID=
EOF
}

generate_support_files() {
  # The compose file bind-mounts these; a fresh checkout doesn't have them.
  if [ ! -f "$DOCKER_DIR/s3_config/s3.selfhost.json" ]; then
    mkdir -p "$DOCKER_DIR/s3_config"
    cat > "$DOCKER_DIR/s3_config/s3.selfhost.json" <<EOF
{
  "identities": [
    {
      "name": "anonymous",
      "actions": ["Read:cg-media"]
    },
    {
      "name": "cg_admin_user",
      "credentials": [
        { "accessKey": "cgadmin", "secretKey": "$(grep '^S3_SECRET=' "$ENV_FILE" | cut -d= -f2)" }
      ],
      "actions": ["Admin", "Read", "List", "Tagging", "Write"]
    }
  ]
}
EOF
  fi
  if [ ! -f "$DOCKER_DIR/vapid_keys.json" ]; then
    # Web-push VAPID pair (P-256, base64url raw keys — what web-push expects).
    node - > "$DOCKER_DIR/vapid_keys.json" <<'EOF'
const { generateKeyPairSync } = require("node:crypto");
const { publicKey, privateKey } = generateKeyPairSync("ec", { namedCurve: "P-256" });
const pubJwk = publicKey.export({ format: "jwk" });
const privJwk = privateKey.export({ format: "jwk" });
const b64u = (s) => s.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
const pub = Buffer.concat([Buffer.from([4]), Buffer.from(pubJwk.x, "base64url"), Buffer.from(pubJwk.y, "base64url")]);
console.log(JSON.stringify({
  publicKey: b64u(pub.toString("base64")),
  privateKey: b64u(Buffer.from(privJwk.d, "base64url").toString("base64")),
  subject: "mailto:conformance@invalid.example",
}, null, 2));
EOF
  fi
  if [ ! -f "$DOCKER_DIR/selfhost/certs/server.crt" ]; then
    # Self-signed cert for the mediasoup HTTPS/WSS listener.
    mkdir -p "$DOCKER_DIR/selfhost/certs"
    openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
      -keyout "$DOCKER_DIR/selfhost/certs/server.key" \
      -out "$DOCKER_DIR/selfhost/certs/server.crt" \
      -days 30 -nodes -subj "/CN=conformance.invalid" 2>/dev/null
  fi
}

wait_for_api() {
  echo "waiting for the API on port ${HTTP_PORT}..."
  for i in $(seq 1 60); do
    if curl -fsS "http://127.0.0.1:${HTTP_PORT}/api/v2/Instance/config" > /dev/null 2>&1; then
      echo "API is up: http://127.0.0.1:${HTTP_PORT}"
      return 0
    fi
    sleep 2
  done
  echo "API did not come up within 120s; container status:" >&2
  compose ps >&2
  return 1
}

case "${1:-}" in
  up)
    generate_env
    generate_support_files
    compose up -d
    echo "waiting for migrations..."
    if ! compose wait migrate-db >/dev/null 2>&1 || \
       [ "$(docker inspect -f '{{.State.ExitCode}}' cg-conformance-migrate-db-1)" != "0" ]; then
      echo "migrate-db failed:" >&2
      compose logs migrate-db | tail -20 >&2
      exit 1
    fi
    wait_for_api
    echo "run the suite with: CG_BASE_URL=http://127.0.0.1:${HTTP_PORT} yarn test"
    ;;
  down)
    [ -f "$ENV_FILE" ] || generate_env
    compose down -v --remove-orphans
    rm -f "$ENV_FILE"
    echo "conformance instance removed (volumes deleted)."
    ;;
  status)
    [ -f "$ENV_FILE" ] || generate_env
    compose ps
    ;;
  *)
    echo "Usage: $0 {up|down|status}" >&2
    exit 1
    ;;
esac
