#!/bin/bash
# Initializes a self-hosted Common Ground instance:
#   - generates docker/.env.selfhost with fresh random secrets
#   - generates docker/s3_config/s3.selfhost.json (matching S3 secret)
#   - generates a self-signed cert for the internal caddy->mediasoup hop
#
# Usage: ./init.sh <domain> <acme-email> [id-domain] [public-ip]
#   e.g.: ./init.sh chat.example.org admin@example.org
#
# Safe to re-run: existing files are never overwritten.
set -euo pipefail
cd "${0%/*}/.."   # docker/

CG_DOMAIN="${1:-}"
CG_ACME_EMAIL="${2:-}"
CG_ID_DOMAIN="${3:-id.${CG_DOMAIN}}"
CG_PUBLIC_IP="${4:-}"

if [ -z "$CG_DOMAIN" ] || [ -z "$CG_ACME_EMAIL" ]; then
  echo "Usage: $0 <domain> <acme-email> [id-domain] [public-ip]"
  echo "  e.g. $0 chat.example.org admin@example.org"
  exit 1
fi

if [ -z "$CG_PUBLIC_IP" ]; then
  echo "Detecting public IP..."
  CG_PUBLIC_IP=$(curl -4 -fsS --max-time 10 https://api.ipify.org || true)
  if [ -z "$CG_PUBLIC_IP" ]; then
    echo "Could not detect public IP; pass it as the 4th argument."
    exit 1
  fi
  echo "Public IP: $CG_PUBLIC_IP"
fi

rand() { openssl rand -hex "$1"; }

if [ -f .env.selfhost ]; then
  echo ".env.selfhost already exists, leaving it untouched."
else
  S3_SECRET_GEN=$(rand 48)
  cat > .env.selfhost <<EOF
# Generated by docker/selfhost/init.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# KEEP THIS FILE SECRET — it contains all credentials of your instance.

CG_DOMAIN=${CG_DOMAIN}
CG_ID_DOMAIN=${CG_ID_DOMAIN}
CG_ACME_EMAIL=${CG_ACME_EMAIL}
CG_PUBLIC_IP=${CG_PUBLIC_IP}

PG_SU_PASSWORD=$(rand 24)
PG_WRITER_PASSWORD=$(rand 24)
PG_READER_PASSWORD=$(rand 24)
PG_MEDIASOUP_PASSWORD=$(rand 24)
REDIS_PASSWORD=$(rand 24)
REDIS_SECRET=$(rand 24)
S3_SECRET=${S3_SECRET_GEN}

# resource tuning (defaults are sized for a 16 GB machine)
REDIS_MAXMEMORY=512mb
SEAWEED_VOLUME_LIMIT_MB=1024
MEDIASOUP_DISABLE_LIBURING=true
BUILDER_UID=$(id -u)
BUILDER_GID=$(id -g)

# bot accounts (all limits are per active owner/token; comma-separate platform operator user UUIDs)
PLATFORM_OPERATOR_USER_IDS=
BOT_USER_OWNER_LIMIT=5
BOT_COMMUNITY_OWNER_LIMIT=10
BOT_PLATFORM_OWNER_LIMIT=10
BOT_ACTIVE_TOKEN_LIMIT=10
BOT_API_RATE_LIMIT_PER_MINUTE=120
BOT_MESSAGE_RATE_LIMIT_PER_MINUTE=30

### Optional third-party integrations — leave empty to disable the feature.

# email delivery (SendGrid). Without it, email login/notifications are unavailable.
SENDGRID_API_KEY=
EMAIL_FROM=no-reply@${CG_DOMAIN}

# reCAPTCHA v2. Without it, registration runs without captcha — fine for
# small/private instances, risky for open ones.
CG_RECAPTCHA_SITE_KEY=
GOOGLE_RECAPTCHA_SECRET_KEY=

# Blockchain RPC endpoints (token-gated roles, balances, premium payments).
# The QUIKNODE_* names are historical — any JSON-RPC URL works. Defaults are
# free public endpoints (rate-limited but fine for small instances); swap in
# paid endpoints (QuikNode, Alchemy, Infura, ...) for heavier use.
# NOTE: the event listener needs unfiltered ranged eth_getLogs; many public
# endpoints restrict that method (e.g. all *.publicnode.com since 2026-07),
# so test with an unfiltered eth_getLogs call before swapping one in.
# CG_ACTIVE_CHAINS controls which chains the instance offers (backend workers
# AND the chain lists in the UI) — keep it in sync with the endpoints you set.
CG_ACTIVE_CHAINS=eth,arbitrum,xdai,base,matic,lukso
QUIKNODE_ETH=https://eth.drpc.org
QUIKNODE_BSC=https://bsc.blockrazor.xyz
QUIKNODE_MATIC=https://polygon.drpc.org
QUIKNODE_XDAI=https://rpc.gnosischain.com
QUIKNODE_FANTOM=https://rpc.fantom.network
QUIKNODE_AVAX=https://avalanche.drpc.org
QUIKNODE_ARBITRUM=https://arb1.arbitrum.io/rpc
QUIKNODE_OPTIMISM=https://optimism.drpc.org
QUIKNODE_BASE=https://mainnet.base.org
INFURA_LINEA=https://linea.drpc.org
QUIKNODE_ARBITRUM_NOVA=https://nova.arbitrum.io/rpc
QUIKNODE_CELO=https://celo.drpc.org
QUIKNODE_POLYGON_ZKEVM=https://zkevm-rpc.com
QUIKNODE_SCROLL=https://rpc.scroll.io
QUIKNODE_ZKSYNC=https://mainnet.era.zksync.io
QUIKNODE_LUKSO=https://rpc.mainnet.lukso.network/

# Token staking (docs/ROADMAP-staking.md): users time-lock an ERC-20 onchain
# and earn Spark while it is locked. Off until STAKING_CHAIN,
# STAKING_TOKEN_ADDRESS and STAKING_CONTRACT_ADDRESS are all set (deploy your
# own CgStaking instance — see contracts/staking/README.md). The chain must be
# in CG_ACTIVE_CHAINS. STAKING_BASE_RATE is Spark per token per 365 days.
#STAKING_CHAIN=eth
#STAKING_TOKEN_ADDRESS=
#STAKING_CONTRACT_ADDRESS=
#STAKING_BASE_RATE=0.012
#STAKING_MIN_LOCK_DAYS=7
#STAKING_MAX_LOCK_DAYS=730

# Twitter/X login (v1 consumer keys drive the login feature; without them
# the X buttons are hidden)
TWITTER_CALLBACK_URL=https://${CG_DOMAIN}/twitter-callback
TWITTER_API_KEY=
TWITTER_API_SECRET=
TWITTER_OAUTH2_CLIENT_ID=
TWITTER_OAUTH2_CLIENT_SECRET=

# SumSub KYC (without keys, KYC steps show as unavailable)
SUMSUB_APP_TOKEN=
SUMSUB_SECRET_KEY=

# Mailchimp (CG-updates newsletter list; without it, subscription state is
# kept locally only)
MAILCHIMP_API_KEY=
MAILCHIMP_LIST_ID=

# Giphy Web SDK key (https://developers.giphy.com). Without it the GIF
# picker is hidden.
CG_GIPHY_API_KEY=

# WalletConnect Cloud project id (https://cloud.walletconnect.com). Project
# ids are origin-allowlisted, so create your own for your domain; without it
# WalletConnect-based wallets may fail to connect (injected wallets like
# MetaMask still work).
CG_WALLETCONNECT_PROJECT_ID=
EOF
  chmod 600 .env.selfhost
  echo "Wrote .env.selfhost"
fi

if [ -f s3_config/s3.selfhost.json ]; then
  echo "s3_config/s3.selfhost.json already exists, leaving it untouched."
else
  S3_SECRET_VAL=$(grep '^S3_SECRET=' .env.selfhost | cut -d= -f2)
  cat > s3_config/s3.selfhost.json <<EOF
{
  "identities": [
    {
      "name": "anonymous",
      "actions": [
        "Read:cg-media"
      ]
    },
    {
      "name": "cg_admin_user",
      "credentials": [
        {
          "accessKey": "cgadmin",
          "secretKey": "${S3_SECRET_VAL}"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "List",
        "Tagging",
        "Write"
      ]
    }
  ]
}
EOF
  chmod 600 s3_config/s3.selfhost.json
  echo "Wrote s3_config/s3.selfhost.json"
fi

if [ -f selfhost/certs/server.crt ]; then
  echo "selfhost/certs/server.crt already exists, leaving it untouched."
else
  mkdir -p selfhost/certs
  openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -subj "/CN=mediasoup" \
    -keyout selfhost/certs/server.key \
    -out selfhost/certs/server.crt 2>/dev/null
  chmod 644 selfhost/certs/server.crt
  chmod 600 selfhost/certs/server.key
  echo "Wrote selfhost/certs/ (internal cert for the caddy->mediasoup hop)"
fi

echo
echo "Initialization complete. Next steps:"
echo "  1. Point DNS A/AAAA records for ${CG_DOMAIN} and ${CG_ID_DOMAIN} to ${CG_PUBLIC_IP}"
echo "  2. Open ports 80, 443, 4443 (tcp) and 40000-40099 (udp) in your firewall"
echo "  3. Run: ./selfhost/selfhost.sh build"
echo "  4. Run: ./selfhost/selfhost.sh up"
